{% set name = "uncommitted" %}
{% set version = "2.1" %}
{% set sha256 = "ae2b4f79b5f515a5eb4d3e28318d535f9496458a9bb2e8e4ba5195312b114658" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install
  preserve_egg_dir: True
  entry_points:
    - uncommitted = uncommitted.command:main

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - uncommitted

  commands:
    - uncommitted --help

about:
  home: https://github.com/brandon-rhodes/uncommitted
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Scan filesystem for changes not committed to version control'
  dev_url: https://github.com/brandon-rhodes/uncommitted

extra:
  recipe-maintainers:
    - proinsias
