{% set name = "uncommitted" %}
{% set version = "2.2" %}
{% set sha256 = "11bec8509649810561e3940c38ad9e3dec54a2c98b71ea47f5dad8ab874edffd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  preserve_egg_dir: True
  entry_points:
    - uncommitted = uncommitted.command:main

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - uncommitted

  commands:
    - uncommitted --help

about:
  home: https://github.com/brandon-rhodes/uncommitted
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Scan filesystem for changes not committed to version control'
  dev_url: https://github.com/brandon-rhodes/uncommitted

extra:
  recipe-maintainers:
    - proinsias
