travis:
  secure:
    BINSTAR_TOKEN: JM8Cjyv5Q3tolXVLahcA1Kipr62W0An0XPP+VcOcjJUlpwa7bTNvdQc8PrhbqboLkEMk8Q8u5sBQ1YS0B0hMkImmgkW7czZb10qc6Y8w/nxVeIzQaykhTvQKxnrP4rycUBz3tc6LZ1kY4hgrLDz0qBDIJAL7hpzqHl3wjWfU2cF292nCS86KDzaGqmiO/Dv+X82YSq1BddcVuLS3LnIqaQ2vs+W2tcc7z7frysRlYi7apPFRD81lYvUqxAlBj7GThU4J/F8GAJFh4k8EIb3DOK0Y5gVy8LFswKD9R6QFoBzsD72EtmQirH7HBRC/zQqPiteDTKJMmeJfS0qpw6JrzGQzyu/WYXT4YDRV5ea8yg+5i3q63+E/K2hAxKxtuh0xI8oFtOh0Oe7b/LNjt2MFGclZh26LUl15M9KrpEKaOkg/8Xy9wWFZAa5xsEElLj6FEKVtM8qX67+NYKTTA2joPSPvaNSWnGGA2LSR3JjeEZxzWAkFhdpJbQH5VrLfM9O/EGACjjGjDedywZc7JAvs3G4VeUvZRcwUS19GTj1ExsY1svKuOm14eA4SVtZrOUXdaIxrsxMj3bUf64hmvTIzZLVAksDEXRdGOsNARSJ6aBUa1B2/pAhQCqwG7ZiAO+aHPkt/gnCsfw4EOArTrx0ISo5oW6lnYvWiWBxRTwIkQ0Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
